// Defines the shape of a Task and the state slice for Redux.

export interface Task {
  id?: number;           // Generated by backend (SQLite + EF)
  title: string;         // Task name
  isCompleted: boolean;  // Completion status
  createdAt?: string;    // Optional timestamp (from backend)
}

export interface TaskState {
  tasks: Task[];
  loading: boolean;
  error: string | null;
}
